name: 'Terraform'             # workflow name

on:                           # trigger
  workflow_dispatch:          # manual trigger by user input
    inputs:
      tfvars_file:
        description: 'Path to the .tfvars file'
        required: true
        default: 'terraform.tfvars'
      action:
        type: choice
        description: 'Apply or Destroy'
        options:
        - plan
        - validate
        - apply
        - destroy
        required: true
        default: 'plan'

env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:       # read access for the github action runner to access my repositories contents
  contents: read

jobs:
  
  CheckOut-Repo:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: terraform-eks

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

  Setting-Up-Terraform:
    runs-on: ubuntu-latest
    
    needs: CheckOut-Repo

    steps:
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.4

  Terraform-Initializing:
    runs-on: ubuntu-latest
    needs: Setting-Up-Terraform

    steps:
      - name: Terraform Init
        working-directory: terraform-eks
        run: terraform init

  Terraform-Action:
    runs-on: ubuntu-latest
    needs: Terraform-Initializing

    steps:
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: terraform-eks
        run: |
          terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -input=false
      
      - name: Terraform Validate
        if: ${{ github.event.inputs.action == 'validate' }}
        working-directory: terraform-eks
        run: |
          terraform validate -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: terraform-eks
        run: terraform apply -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: terraform-eks
        run: terraform destroy -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false