name: 'Terraform'             # Workflow name

on:                           # Trigger
  workflow_dispatch:          # Manual trigger by user input
    inputs:
      tfvars_file:
        description: 'Path to the .tfvars file'
        required: true
        default: 'terraform.tfvars'
      action:
        type: choice
        description: 'Plan, Validate, Apply, or Destroy'
        options:
        - plan
        - validate
        - apply
        - destroy
        required: true
        default: 'plan'

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  contents: read

jobs:
  
  CheckOut-Repo:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List the repository contents
        run: ls -alth /home/runner/work/github_action-terraform-eks-helm-argocd/

  Setting-Up-Terraform:
    runs-on: ubuntu-latest
    needs: CheckOut-Repo

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4

  Terraform-Initializing:
    runs-on: ubuntu-latest
    needs: Setting-Up-Terraform

    steps:
      - name: List the working directory and confirm path
        run: |
          echo "Current directory:"
          pwd
          echo "Listing contents of the current directory:"
          ls -alth

      - name: Terraform Init
        working-directory: /home/runner/work/github_action-terraform-eks-helm-argocd/github_action-terraform-eks-helm-argocd/terraform-eks # Change this path accordingly
        run: terraform init

  Terraform-Action:
    runs-on: ubuntu-latest
    needs: Terraform-Initializing

    steps:
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: /home/runner/work/github_action-terraform-eks-helm-argocd/github_action-terraform-eks-helm-argocd/terraform-eks # Change this path accordingly
        run: |
          terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -input=false
      
      - name: Terraform Validate
        if: ${{ github.event.inputs.action == 'validate' }}
        working-directory: /home/runner/work/github_action-terraform-eks-helm-argocd/github_action-terraform-eks-helm-argocd/terraform-eks # Change this path accordingly
        run: terraform validate

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: /home/runner/work/github_action-terraform-eks-helm-argocd/github_action-terraform-eks-helm-argocd/terraform-eks # Change this path accordingly
        run: terraform apply -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: /home/runner/work/github_action-terraform-eks-helm-argocd/github_action-terraform-eks-helm-argocd/terraform-eks # Change this path accordingly
        run: terraform destroy -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false
